# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 01:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='email address')),
                ('date_of_birth', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('facebook_id', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=300, null=True)),
                ('link', models.URLField(blank=True, max_length=300, null=True)),
                ('username', models.CharField(blank=True, max_length=300)),
                ('gender', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssistanceTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField()),
                ('type_of_assistance', models.TextField()),
                ('date_needed', models.DateField()),
                ('status', models.IntegerField(choices=[(1, 'Critical'), (2, 'Urgent'), (3, 'Normal'), (4, 'Desirable')], default=3)),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssistanceTicketReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_reacted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AssistanceTicket')),
            ],
        ),
        migrations.CreateModel(
            name='FacebookSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=103, unique=True)),
                ('expires', models.IntegerField(null=True)),
                ('uid', models.BigIntegerField(null=True, unique=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsDemands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_type', models.IntegerField(choices=[(1, 'food pack'), (2, 'water pack (2l)'), (3, 'blanket'), (4, 'pain killer'), (5, 'sedative')])),
                ('qty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HelpProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelter_name', models.CharField(max_length=50)),
                ('location_lat', models.FloatField()),
                ('location_long', models.FloatField()),
                ('address', models.CharField(max_length=100)),
                ('max_capacity', models.IntegerField()),
                ('people_inside', models.IntegerField()),
                ('people_coming', models.IntegerField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.HelpProvider')),
            ],
        ),
        migrations.AddField(
            model_name='goodsdemands',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Shelter'),
        ),
        migrations.AddField(
            model_name='goodsdemands',
            name='who_demands',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='facebooksession',
            unique_together=set([('user', 'uid'), ('access_token', 'expires')]),
        ),
    ]
