# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 01:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistanceTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField()),
                ('type_of_assistance', models.TextField()),
                ('date_needed', models.DateField()),
                ('status', models.IntegerField(choices=[(1, 'Critical'), (2, 'Urgent'), (3, 'Normal'), (4, 'Desirable')], default=3)),
            ],
        ),
        migrations.CreateModel(
            name='AssistanceTicketReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsDemands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_type', models.IntegerField(choices=[(1, 'food pack'), (2, 'water pack (2l)'), (3, 'blanket'), (4, 'pain killer'), (5, 'sedative')])),
                ('qty', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='helpticket',
            name='user_created',
        ),
        migrations.AddField(
            model_name='helpprovider',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='helpprovider',
            name='password',
            field=models.CharField(default='lol', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shelter',
            name='address',
            field=models.CharField(default='blah', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shelter',
            name='max_capacity',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shelter',
            name='people_coming',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shelter',
            name='people_inside',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shelter',
            name='shelter_name',
            field=models.CharField(default='blah', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='helpprovider',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='facebook_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='Affected',
        ),
        migrations.DeleteModel(
            name='HelpTicket',
        ),
        migrations.AddField(
            model_name='goodsdemands',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Shelter'),
        ),
        migrations.AddField(
            model_name='goodsdemands',
            name='who_demands',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assistanceticketreaction',
            name='person_reacted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assistanceticketreaction',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AssistanceTicket'),
        ),
        migrations.AddField(
            model_name='assistanceticket',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
